export const experiencesData = [
  {
    id: 1,
    slug: "staff-event-stock-summit-ui",
    title: "Staff Event Stock-Summit UI",
    company: "Staff Event",
    period: "2024",
    date: "2024",
    image: "/img/IMG_3833.jpg",
    description:
      "Berperan sebagai staff divisi event dan MC pada acara Seminar Stock-Summit UI. Mengelola koordinasi acara dan memfasilitasi jalannya seminar dengan audience yang besar.",
    responsibilities: [
      "Mengelola koordinasi teknis dan logistik acara seminar",
      "Menjadi MC untuk membawakan acara di hadapan ratusan peserta",
      "Memfasilitasi sesi Q&A dan interaksi dengan pembicara",
      "Berkoordinasi dengan tim untuk memastikan timeline acara berjalan sesuai rencana",
      "Membantu registrasi dan handling peserta seminar",
    ],
    gallery: ["/img/IMG_3833.jpg"],
    icon: "📋",
  },
  {
    id: 2,
    slug: "bpjs-ketenagakerjaan-internship",
    title: "BPJS Ketenagakerjaan Internship",
    company: "BPJS Ketenagakerjaan",
    period: "Agustus 2025 - November 2025",
    date: "Agustus 2025 - November 2025",
    image: "/img/bpjs.jpg",
    description:
      "Magang sebagai Full-Stack Developer di BPJS Ketenagakerjaan, bertanggung jawab dalam pengembangan aplikasi internal perusahaan.",
    responsibilities: [
      "Mengimplementasikan Vue.js, Node.js(Express.js), PHP, dan VMS sebagai tech stack utama",
      "Menggunakan Figma untuk mendesain antarmuka pengguna (UI) situs web internal",
      "Bekerja sama dengan tim di Figma untuk mendesain fitur situs web internal",
      "Mengambil peran sebagai Insinyur Back End, fokus pada logika sisi server",
      "Membuat REST APIs menggunakan Node.js (Express.js) dan PHP",
      "Menerapkan integrasi frontend dengan formulir, tombol, dan validasi berdasarkan desain Figma",
      "Menerapkan alur create, read, dan update antara Database ⇄ API ⇄ Frontend",
    ],
    gallery: [
      "/img/experience_folder/gallery_bpjs/bpjs1.jpeg",
      "/img/experience_folder/gallery_bpjs/bpjs2.jpeg",
    ],
    icon: "💼",
  },
  {
    id: 3,
    slug: "otoritas-jasa-keuangan-internship",
    title: "Otoritas Jasa Keuangan Internship",
    company: "Otoritas Jasa Keuangan",
    period: "Februari 2026 - Mei 2026",
    date: "Februari 2026 - Mei 2026",
    image: "/img/damOJK.jpg",
    description: "Magang di bagian Departmen Organisasi, SDM & Budaya.",
    responsibilities: [
      "Mengelola digitalisasi dan entri data untuk lebih dari 100+ dokumen arsip strategis ke dalam sistem basis data Excel dengan tingkat akurasi tinggi guna memastikan ketersediaan data bagi keperluan proyeksi organisasi mendatang.",
    ],
    gallery: [
      "/img/experience_folder/gallery_ojk/dam-ojk.jpg",
      "/img/experience_folder/gallery_ojk/pct8.1.jpeg",
      "/img/experience_folder/gallery_ojk/pct8.2.jpeg",
    ],
    icon: "💼",
  },
]
